export enum IdType {
    AuditIssues = 0,
    CriticalHighIssues = 2,
    ModerateLowIssues = 3,
    AuditActions = 4,
    CriticalHighActions = 5,
    ModerateLowActions = 6,
    HighRisks = 7,
    ModerateRisks = 8,
    LowRisks = 9,
    SevereIncidents = 10,
    MajorIncidents = 11,
    MinorIncidents = 12,
    NoImpactIncidents = 13,
    WIRMActions = 14,
    Documentation = 15,
    Hygiene = 16,
    Training = 17,
    RecoveryResiliency = 18,
    Entitlements = 19,
    T30Alerts = 1
}